data_path: ../../data
model: 
  name: klue/roberta-base
  pool: True
  metric: dot
train:
  output_dir: ./models/retrieval
  epoch: 5
  learning_rate: 2e-5
  batch_size: 16
  weight_decay: 0.01
topk: 5