data_path: ../data # wikipedia_documents.json 대신 wiki_name의 csv 파일 필요
model: 
  name: klue/roberta-base
  pool: True
  metric: dot
train:
  output_dir: /data/ephemeral/home/jh/level2-mrc-nlp-06/models/dense_retrieval_model
  epoch: 1
  learning_rate: 2e-5
  batch_size: 16
  weight_decay: 0.01
topk: 5